# Generated by Django 6.0.5 on 2026-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_detectionlog_loginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='DetectionLog',
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
